<a href="https://colab.research.google.com/github/Rafia-Shaikh-eng/Data-Science-Analytics/blob/main/1_combining_data_solution_ETL_Transform.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Combining Data

Practice combining data from two different data sets. In the same folder as this Jupyter notebook, there are two csv files:
* rural_population_percent.csv
* electricity_access_percent.csv

They both come from the World Bank Indicators data.
* https://data.worldbank.org/indicator/SP.RUR.TOTL.ZS
* https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS

The rural populaton data represents the percent of a country's population that is rural over time. The electricity access data shows the percentage of people with access to electricity.

In this exercise, you will combine these two data sets together into one pandas data frame.

# Exercise 1

Combine the two data sets using the [pandas concat method](https://pandas.pydata.org/pandas-docs/stable/merging.html). In other words, find the union of the two data sets.

In [ ]:
# TODO: import the pandas library
import pandas as pd

# TODO: read in each csv file into a separate variable
# HINT: remember from the Extract material that these csv file have some formatting issues
df_rural = pd.read_csv('rural_population_percent.csv', skiprows=4)
df_electricity = pd.read_csv('electricity_access_percent.csv', skiprows=4)

# TODO: remove the 'Unnamed:62' column from each data set
df_rural.drop('Unnamed: 62', axis=1, inplace=True)
df_electricity.drop('Unnamed: 62', axis=1, inplace=True)

# TODO: combine the two data sets together using the concat method
df = pd.concat([df_rural, df_electricity])

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,Rural population (% of total population),SP.RUR.TOTL.ZS,49.224000,49.23900,49.25400,49.27000,49.285000,49.30000,...,56.217000,56.579000,56.941000,57.302000,57.636000,57.942000,58.221000,58.472000,58.696000,58.893000
1,Afghanistan,AFG,Rural population (% of total population),SP.RUR.TOTL.ZS,91.779000,91.49200,91.19500,90.89000,90.574000,90.25000,...,76.054000,75.687000,75.311000,74.926000,74.532000,74.129000,73.718000,73.297000,72.868000,72.430000
2,Angola,AGO,Rural population (% of total population),SP.RUR.TOTL.ZS,89.565000,89.20200,88.79600,88.37600,87.942000,87.49600,...,61.491000,60.701000,59.903000,59.100000,58.301000,57.510000,56.726000,55.950000,55.181000,54.422000
3,Albania,ALB,Rural population (% of total population),SP.RUR.TOTL.ZS,69.295000,69.05700,68.98500,68.91400,68.842000,68.77000,...,50.009000,48.924000,47.837000,46.753000,45.670000,44.617000,43.591000,42.593000,41.624000,40.684000
4,Andorra,AND,Rural population (% of total population),SP.RUR.TOTL.ZS,41.550000,39.01700,36.53800,34.12800,31.795000,29.55500,...,11.133000,11.648000,12.183000,12.740000,13.292000,13.835000,14.367000,14.885000,15.388000,15.873000
5,Arab World,ARB,Rural population (% of total population),SP.RUR.TOTL.ZS,68.708026,67.96558,67.21982,66.45096,65.652964,64.81343,...,44.518882,44.156769,43.804530,43.463488,43.128649,42.803731,42.491260,42.191790,41.906071,41.631967
6,United Arab Emirates,ARE,Rural population (% of total population),SP.RUR.TOTL.ZS,26.500000,25.61700,24.75200,23.90700,23.081000,22.27700,...,16.623000,16.277000,15.945000,15.625000,15.316000,15.019000,14.734000,14.459000,14.196000,13.942000
7,Argentina,ARG,Rural population (% of total population),SP.RUR.TOTL.ZS,26.389000,25.78300,25.23300,24.69100,24.156000,23.63100,...,9.378000,9.205000,9.034000,8.867000,8.705000,8.548000,8.396000,8.249000,8.107000,7.970000
8,Armenia,ARM,Rural population (% of total population),SP.RUR.TOTL.ZS,48.725000,47.85300,46.98100,46.11100,45.242000,44.37800,...,36.003000,36.211000,36.420000,36.629000,36.839000,37.025000,37.188000,37.327000,37.442000,37.533000
9,American Samoa,ASM,Rural population (% of total population),SP.RUR.TOTL.ZS,33.789000,33.35900,32.93200,32.50700,32.084000,31.66600,...,12.201000,12.303000,12.406000,12.500000,12.587000,12.666000,12.736000,12.798000,12.852000,12.897000
10,Antigua and Barbuda,ATG,Rural population (% of total population),SP.RUR.TOTL.ZS,60.344000,60.96000,61.57300,62.18300,62.789000,63.39000,...,72.594000,73.181000,73.761000,74.333000,74.865000,75.357000,75.810000,76.227000,76.607000,76.953000
11,Australia,AUS,Rural population (% of total population),SP.RUR.TOTL.ZS,18.471000,18.05900,17.66300,17.27300,16.890000,16.51500,...,11.555000,11.410000,11.267000,11.125000,10.985000,10.847000,10.711000,10.577000,10.446000,10.317000
12,Austria,AUT,Rural population (% of total population),SP.RUR.TOTL.ZS,35.280000,35.18600,35.13700,35.08700,35.038000,34.98900,...,34.159000,34.153000,34.148000,34.142000,34.136000,34.116000,34.081000,34.032000,33.968000,33.890000
13,Azerbaijan,AZE,Rural population (% of total population),SP.RUR.TOTL.ZS,47.337000,47.63600,47.93600,48.23600,48.536000,48.83600,...,47.010000,46.810000,46.599000,46.377000,46.144000,45.900000,45.645000,45.380000,45.105000,44.819000
14,Burundi,BDI,Rural population (% of total population),SP.RUR.TOTL.ZS,97.923000,97.88500,97.84600,97.80700,97.767000,97.70600,...,89.882000,89.624000,89.359000,89.088000,88.811000,88.528000,88.239000,87.943000,87.641000,87.333000
15,Belgium,BEL,Rural population (% of total population),SP.RUR.TOTL.ZS,7.540000,7.44600,7.32100,7.16500,7.012000,6.86300,...,2.454000,2.406000,2.359000,2.313000,2.268000,2.224000,2.182000,2.142000,2.103000,2.066000
16,Benin,BEN,Rural population (% of total population),SP.RUR.TOTL.ZS,90.725000,90.14400,89.53000,88.88200,88.199000,87.48100,...,58.922000,58.539000,58.146000,57.744000,57.333000,56.914000,56.486000,56.050000,55.605000,55.153000
17,Burkina Faso,BFA,Rural population (% of total population),SP.RUR.TOTL.ZS,95.300000,95.20400,95.10700,95.00700,94.905000,94.80200,...,76.007000,75.172000,74.335000,73.495000,72.654000,71.814000,70.976000,70.141000,69.312000,68.489000
18,Bangladesh,BGD,Rural population (% of total population),SP.RUR.TOTL.ZS,94.865000,94.72200,94.50200,94.27300,94.036000,93.78900,...,71.032000,70.291000,69.538000,68.775000,68.010000,67.247000,66.484000,65.723000,64.965000,64.210000
19,Bulgaria,BGR,Rural population (% of total population),SP.RUR.TOTL.ZS,62.900000,61.21800,59.50600,57.77000,56.013000,54.24500,...,28.378000,28.037000,27.698000,27.362000,27.029000,26.700000,26.374000,26.052000,25.734000,25.419000
20,Bahrain,BHR,Rural population (% of total population),SP.RUR.TOTL.ZS,17.680000,17.66300,17.64500,17.62800,17.611000,17.50000,...,11.532000,11.500000,11.465000,11.425000,11.381000,11.333000,11.281000,11.225000,11.165000,11.101000
21,"Bahamas, The",BHS,Rural population (% of total population),SP.RUR.TOTL.ZS,40.288000,39.54600,38.80700,38.07400,37.358000,36.65700,...,17.558000,17.505000,17.451000,17.394000,17.333000,17.268000,17.199000,17.126000,17.049000,16.969000
22,Bosnia and Herzegovina,BIH,Rural population (% of total population),SP.RUR.TOTL.ZS,80.960000,80.31400,79.56300,78.79100,77.996000,77.18300,...,60.839000,60.817000,60.774000,60.709000,60.622000,60.514000,60.384000,60.233000,60.060000,59.865000
23,Belarus,BLR,Rural population (% of total population),SP.RUR.TOTL.ZS,67.599000,66.47800,65.33700,64.17800,63.000000,61.87300,...,26.274000,25.828000,25.385000,24.954000,24.533000,24.123000,23.723000,23.333000,22.954000,22.584000
24,Belize,BLZ,Rural population (% of total population),SP.RUR.TOTL.ZS,45.972000,46.28000,46.59000,46.89900,47.210000,47.51900,...,54.499000,54.768000,55.037000,55.282000,55.504000,55.702000,55.876000,56.027000,56.155000,56.258000
25,Bermuda,BMU,Rural population (% of total population),SP.RUR.TOTL.ZS,0.000000,0.00000,0.00000,0.00000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
26,Bolivia,BOL,Rural population (% of total population),SP.RUR.TOTL.ZS,63.238000,62.94100,62.64300,62.34400,62.043000,61.74300,...,34.450000,34.009000,33.574000,33.145000,32.721000,32.304000,31.893000,31.488000,31.089000,30.697000
27,Brazil,BRA,Rural population (% of total population),SP.RUR.TOTL.ZS,53.861000,52.87800,51.90100,50.92200,49.941000,48.96300,...,16.251000,15.956000,15.665000,15.377000,15.099000,14.829000,14.567000,14.313000,14.067000,13.828000
28,Barbados,BRB,Rural population (% of total population),SP.RUR.TOTL.ZS,63.223000,63.15100,63.07800,63.00500,62.932000,62.85900,...,67.590000,67.765000,67.940000,68.095000,68.231000,68.348000,68.446000,68.525000,68.585000,68.626000
29,Brunei Darussalam,BRN,Rural population (% of total population),SP.RUR.TOTL.ZS,56.599000,54.77200,52.93000,51.08000,49.224000,47.37500,...,25.254000,24.866000,24.490000,24.128000,23.777000,23.439000,23.113000,22.798000,22.495000,22.203000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,95.186103,95.441090,95.801052,96.161153,96.522279,96.922377,96.936467,97.183215,97.742979,NaN
235,Timor-Leste,TLS,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,41.100101,43.844738,38.000000,49.385078,52.174774,54.973484,57.778198,67.281534,63.394138,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,94.760384,95.008710,95.297786,95.910895,96.376501,97.506184,96.325711,97.493216,97.671447,NaN
237,Tonga,TON,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,90.780235,91.511932,92.261650,92.175456,92.800000,94.588905,95.380676,96.175453,97.020000,NaN
238,South Asia (IDA & IBRD),TSA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,70.641563,74.025057,75.117519,69.326529,79.352935,79.318324,81.448690,86.513987,85.569150,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,31.973327,32.490060,32.633561,34.880128,35.770348,36.542705,37.760013,38.459815,42.813754,NaN
240,Trinidad and Tobago,TTO,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.827667,99.000000,99.298363,99.736145,99.936935,99.992935,100.000000,100.000000,100.000000,NaN
241,Tunisia,TUN,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.400000,99.500000,99.500000,99.500000,99.500000,99.700000,99.800000,100.000000,100.000000,NaN
242,Turkey,TUR,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.806900,99.310745,100.000000,99.910782,99.985657,99.999252,100.000000,100.000000,100.000000,NaN
243,Tuvalu,TUV,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,96.450043,96.779938,97.127861,97.490799,97.671777,98.249725,98.639702,99.032677,99.426155,NaN
244,Tanzania,TZA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,11.500000,11.200000,14.800000,14.200000,15.300000,16.400000,18.910179,18.500000,32.800000,NaN
245,Uganda,UGA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,13.383857,10.000000,14.769371,14.600000,16.214964,13.900000,20.400000,18.500000,26.700000,NaN
246,Ukraine,UKR,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.782707,99.872482,99.945076,99.985046,99.867491,100.000000,100.000000,100.000000,100.000000,NaN
247,Upper middle income,UMC,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.951365,98.322811,98.775502,98.866005,99.059438,99.214211,99.235891,99.268934,99.379714,NaN
248,Uruguay,URY,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.784355,98.830696,98.989487,99.170000,99.349075,99.611808,99.657085,99.709480,100.000000,NaN
249,United States,USA,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
250,Uzbekistan,UZB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,99.902954,99.955498,99.986694,99.997910,99.999908,100.000000,100.000000,100.000000,100.000000,NaN
251,St. Vincent and the Grenadines,VCT,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,90.470222,91.837242,93.222282,94.622345,96.034424,97.455513,98.598648,99.455063,100.000000,NaN
252,"Venezuela, RB",VEN,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,98.630798,98.710304,98.807846,98.840000,99.044968,99.178551,99.318146,99.460739,99.603836,NaN
253,British Virgin Islands,VGB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
255,Vietnam,VNM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,95.208260,96.100000,97.591133,99.000000,100.000000,100.000000,99.200000,100.000000,100.000000,NaN
256,Vanuatu,VUT,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,33.873974,33.291115,36.898365,38.434589,39.982830,31.700000,43.103348,44.669613,57.820000,NaN
257,World,WLD,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,82.278317,83.211382,83.539093,82.504609,85.041356,85.163456,85.690892,87.028468,87.351269,NaN
258,Samoa,WSM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,94.694328,97.900000,96.606010,96.668575,98.504707,99.255646,97.900000,99.938278,100.000000,NaN
259,Kosovo,XKX,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.794670,98.377060,0.000000,99.430435,99.773651,99.942505,99.993134,100.000000,100.000000,NaN
260,"Yemen, Rep.",YEM,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,60.386539,61.751400,63.134281,64.532181,65.942101,75.600000,66.100000,70.213905,71.642349,NaN
261,South Africa,ZAF,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,81.900000,82.700000,82.900000,84.700000,85.300000,85.400000,86.000000,85.500000,84.200000,NaN
262,Zambia,ZMB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,22.714685,23.235649,22.000000,24.328644,24.894667,25.469702,27.900000,31.100000,27.219337,NaN
263,Zimbabwe,ZWE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,35.457310,43.369082,36.063057,36.900000,36.728878,37.076813,32.300000,33.700000,38.145138,NaN

# Exercise 2 (Challenge)

This exercise is more challenging. Combine the data in the csv file together to the output that look like the following:

|Country Name|Country Code|Year|Rural_Value|Electricity_Value|
|--|--|--|--|--|--|
|Aruba|ABW|1960|49.224|49.239|
... etc.

Order the results in the dataframe by country and then by year

Here are a few pandas methods that should be helpful:
* [melt](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html)
* [merge](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.merge.html)
* [sort_values](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html)

HINT: You can use country name, country code, and the year as common keys between the data sets

In [ ]:
# TODO: merge the data sets together according to the instructions. First, use the
# melt method to change the formatting of each data frame so that it looks like this:
# Country Name, Country Code, Year, Rural Value
# Country Name, Country Code, Year, Electricity Value

df_rural_melt = pd.melt(df_rural,\
                        id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],\
                       var_name = 'Year', value_name='Rural_Value')
df_electricity_melt = pd.melt(df_electricity,\
                              id_vars=['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code'],\
                             var_name='Year', value_name='Electricity_Value')

# TODO: drop any columns from the data frames that aren't needed
df_rural_melt.drop(['Indicator Name', 'Indicator Code'], axis=1, inplace=True)
df_electricity_melt.drop(['Indicator Name', 'Indicator Code'], axis=1, inplace=True)

# TODO: merge the data frames together based on their common columns
# in this case, the common columns are Country Name, Country Code, and Year
df_merge = df_rural_melt.merge(df_electricity_melt, how='outer',\
                               on=['Country Name', 'Country Code', 'Year'])

# TODO: sort the results by country and then by year
df_combined = df_merge.sort_values(['Country Name', 'Year'])
df_combined

      Country Name Country Code  Year  Electricity_Value  Rural_Value
1      Afghanistan          AFG  1960             91.779          NaN
265    Afghanistan          AFG  1961             91.492          NaN
529    Afghanistan          AFG  1962             91.195          NaN
793    Afghanistan          AFG  1963             90.890          NaN
1057   Afghanistan          AFG  1964             90.574          NaN
1321   Afghanistan          AFG  1965             90.250          NaN
1585   Afghanistan          AFG  1966             89.915          NaN
1849   Afghanistan          AFG  1967             89.570          NaN
2113   Afghanistan          AFG  1968             89.214          NaN
2377   Afghanistan          AFG  1969             88.848          NaN
2641   Afghanistan          AFG  1970             88.471          NaN
2905   Afghanistan          AFG  1971             88.083          NaN
3169   Afghanistan          AFG  1972             87.684          NaN
3433   Afghanistan          AFG  1973             87.274          NaN
3697   Afghanistan          AFG  1974             86.851          NaN
3961   Afghanistan          AFG  1975             86.417          NaN
4225   Afghanistan          AFG  1976             85.971          NaN
4489   Afghanistan          AFG  1977             85.513          NaN
4753   Afghanistan          AFG  1978             85.042          NaN
5017   Afghanistan          AFG  1979             84.565          NaN
5281   Afghanistan          AFG  1980             84.319          NaN
5545   Afghanistan          AFG  1981             84.070          NaN
5809   Afghanistan          AFG  1982             83.818          NaN
6073   Afghanistan          AFG  1983             83.563          NaN
6337   Afghanistan          AFG  1984             83.304          NaN
6601   Afghanistan          AFG  1985             83.042          NaN
6865   Afghanistan          AFG  1986             82.777          NaN
7129   Afghanistan          AFG  1987             82.509          NaN
7393   Afghanistan          AFG  1988             82.237          NaN
7657   Afghanistan          AFG  1989             81.962          NaN
...            ...          ...   ...                ...          ...
7655      Zimbabwe          ZWE  1988             72.476          NaN
7919      Zimbabwe          ZWE  1989             71.750          NaN
8183      Zimbabwe          ZWE  1990             71.012    30.357832
8447      Zimbabwe          ZWE  1991             70.262    30.718805
8711      Zimbabwe          ZWE  1992             69.501    28.200000
8975      Zimbabwe          ZWE  1993             69.060    31.436678
9239      Zimbabwe          ZWE  1994             68.665    28.100000
9503      Zimbabwe          ZWE  1995             68.268    32.130077
9767      Zimbabwe          ZWE  1996             67.868    32.459949
10031     Zimbabwe          ZWE  1997             67.466    32.774529
10295     Zimbabwe          ZWE  1998             67.061    33.070751
10559     Zimbabwe          ZWE  1999             66.653    38.400000
10823     Zimbabwe          ZWE  2000             66.242    33.597420
11087     Zimbabwe          ZWE  2001             65.830    33.830868
11351     Zimbabwe          ZWE  2002             65.415    34.200000
11615     Zimbabwe          ZWE  2003             65.521    34.266785
11879     Zimbabwe          ZWE  2004             65.706    34.481380
12143     Zimbabwe          ZWE  2005             65.890    34.701820
12407     Zimbabwe          ZWE  2006             66.074    37.200000
12671     Zimbabwe          ZWE  2007             66.257    35.184479
12935     Zimbabwe          ZWE  2008             66.440    35.457310
13199     Zimbabwe          ZWE  2009             66.622    43.369082
13463     Zimbabwe          ZWE  2010             66.804    36.063057
13727     Zimbabwe          ZWE  2011             66.985    36.900000
13991     Zimbabwe          ZWE  2012             67.166    36.728878
14255     Zimbabwe          ZWE  2013             67.346    37.076813
14519     Zimbabwe          ZWE  2014             67.499    32.300000
14783     Zimbabwe          ZWE  2015             67.624    33.700000
15047     Zimbabwe          ZWE  2016             67.723    38.145138
15311     Zimbabwe          ZWE  2017             67.793          NaN

[15312 rows x 5 columns]